language: python
python:
  - '3.5'

before_script:
  - pip3 install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="main.settings"

services:
  - postgresql

script:
  - ./manage.py test

# safelist
branches:
  only:
    - release