language: python
python:
  - '3.5'

# safelist
branches:
  only:
    - release

before_script:
  - pip3 install -r requirements.txt

env:
  global:
    - SECRET_KEY="zohguiozrhgu62354ézh232ttr2rjé"
    - ENV="PRODUCTION"
    - YOUR_DATABASE_NAME="patate"
    - YOUR_USER_DB="patate"
    - YOUR_PASSWORD_DB="patate"
    - CLOUDINARY_CONFIG_CLOUD_NAME="projectPlannerCloud"
    - CLOUDINARY_CONFIG_API_KEY="patate"
    - CLOUDINARY_CONFIG_API_SECRET="patate"
    - MAILGUN_ACCESS_KEY='patate'
    - MAILGUN_SERVER_NAME='patate'
    - MAILGUN_SENDER_EMAIL_ADDRESS='patate'
  jobs:
  - DJANGO_SETTINGS_MODULE="main.settings"

services:
  - postgresql

script:
  - ./manage.py test



