language: python
python:
  - '3.5'

# safelist
branches:
  only:
    - release

before_script:
  - pip3 install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="main.settings.travis", SECRET_KEY= "jkgnberkjgerzlmighzbigùopi"


services:
  - postgresql

script:
  - ./manage.py test


