language: python
python:
  - '3.5'

# safelist
branches:
  only:
    - release

before_script:
  - pip3 install -r requirements.txt
  - python3 manage.py collectstatic

env:
  global:
    - SECRET_KEY="zohguiozrhgu62354ézh232ttr2rjé"
    - ENV="PRODUCTION"
    - YOUR_DATABASE_NAME=""
    - YOUR_USER_DB=""
    - YOUR_PASSWORD_DB=""
  jobs:
  - DJANGO_SETTINGS_MODULE="main.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test


